### ISSUE TITLE
Most boards listed under HX8K actually use HX4K

### ISSUE THREAD

**Issue by rvalles** [kelu124/awesome-latticeFPGAs#3]
Alhambra II and BlackICE II, for instance.

Please review these.

**Comment by adumont** [comment]
HX4K is actually an HX8K labeled as 4K iirc. It's a marketing stunt, but
the same chip inside.

**Comment by rvalles** [comment]
@adumont 

AIUI they have 8K, but they definitely are not 8K chips. Lattice's software will see 4K, and if you use more on yosys/nextpnr, it'll be at your own risk.

**Comment by kelu124** [comment]
Thanks @rvalles and @adumont .
Indeed, hx4k and hx8k appear under yosys/nextpnr to be the same chip - but definitely not under Lattice's.
Will amend accordingly - or do feel free to push a PR  - whatever comes first =)
